# Generated by Django 2.0.5 on 2018-06-20 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [ 
        ('billing', '0002_invoice_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
