# Generated by Django 2.0.5 on 2018-06-20 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_auto_20180413_1959'),
        ('billing', '0003_auto_20180620_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stripe_charge', to='pinax_stripe.Charge'),
        ),
    ]
