# Generated by Django 2.0.5 on 2018-06-20 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='server_invoice', to='pinax_stripe.Charge'),
        ),
    ]
