# Generated by Django 2.0.5 on 2018-07-28 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0005_auto_20180620_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('card', 'Card'), ('paypal', 'Paypal'), ('other', 'Other')], max_length=32)),
                ('temporary', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('last4', models.CharField(blank=True, max_length=64, null=True)),
                ('brand', models.CharField(blank=True, max_length=64, null=True)),
                ('exp_month', models.CharField(blank=True, max_length=64, null=True)),
                ('exp_year', models.CharField(blank=True, max_length=64, null=True)),
                ('stripe_id', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('billing.userpayment',),
        ),
    ]
