# Generated by Django 2.0.5 on 2018-07-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_userpayment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
