# Generated by Django 2.0.5 on 2018-07-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_userpayment_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
