# Generated by Django 2.0.5 on 2018-07-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_invoice', to='pinax_stripe.Charge'),
        ),
    ]
