# Generated by Django 2.0.5 on 2018-07-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20180728_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='temporary',
            field=models.BooleanField(),
        ),
    ]
