# Generated by Django 2.0.5 on 2018-06-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.CartItem'),
        ),
    ]
