# Generated by Django 2.0.5 on 2018-06-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repair', '0005_auto_20180612_1817'),
        ('store', '0004_auto_20180615_0356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='CartEntry',
        ),
    ]
