# Generated by Django 2.0.5 on 2018-06-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180615_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartentry',
            name='type',
            field=models.CharField(choices=[('Repair', 'Repair'), ('Computer', 'Computer')], default='Repair', max_length=32),
        ),
    ]
