# Generated by Django 2.0.5 on 2018-06-15 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20180615_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartentry',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='store.Cart'),
        ),
        migrations.AlterField(
            model_name='cartentry',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repair.DeviceRepair'),
        ),
    ]
