# Generated by Django 2.0.5 on 2018-07-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cart_temp_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='temp_source',
        ),
    ]
