# Generated by Django 2.0.5 on 2018-06-16 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Order Received', 'Order Received.'), ('Replacement part has shipped', 'Replacement part has shipped.')], max_length=256)),
                ('priority', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='status',
        ),
        migrations.AddField(
            model_name='tracker',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trackerupdate',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='tracker.Tracker'),
        ),
    ]
