# Generated by Django 2.0.5 on 2018-06-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180616_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerupdate',
            name='priority',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
        migrations.AlterField(
            model_name='trackerupdate',
            name='status',
            field=models.CharField(choices=[('Order Received', 'Order Received.'), ('Replacement part has shipped', 'Replacement part has shipped.')], default='Order Received', max_length=256),
        ),
    ]
