# Generated by Django 2.0.5 on 2018-06-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180616_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerupdate',
            name='description',
            field=models.CharField(blank=True, choices=[('Order Received', 'Your order has been successfully placed.'), ('Replacement Shipped', 'Your replacement item is on the way!'), ('Ready for Repair', 'Your replacement has arrived. See below how to continue.'), ('Repair', 'Your device has been received and will be repaired shortly.'), ('Pickup', 'Your device is fixed and ready for pickup!'), ('', '')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='trackerupdate',
            name='status',
            field=models.CharField(choices=[('Order Received', 'Order Received.'), ('Replacement Shipped', 'Replacement Shipped.'), ('Ready for Repair', 'Ready for Repair'), ('Repair', 'Repair'), ('Pickup', 'Pickup'), ('Complete', 'Complete')], default='Order Received', max_length=256),
        ),
    ]
