# Generated by Django 2.0.5 on 2018-06-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20180616_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerupdate',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
