# Generated by Django 2.0.5 on 2018-06-20 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20180616_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='billing.Order'),
        ),
    ]
